# Generated by Django 4.2.16 on 2024-11-16 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.UUIDField()),
                ('report', models.TextField()),
                ('report_url', models.URLField()),
                ('student_id', models.UUIDField()),
            ],
        ),
    ]
